In [4]:
import pandas as pd
import numpy as np
import random as rd
from sklearn.decomposition import PCA
from sklearn import preprocessing
import matplotlib.pyplot as plt

In [7]:
genes = ['gene' + str(i) for i in range(1,101)]
wt = ['wt' + str(i) for i in range(1,6)]
ko = ['ko' + str(i) for i in range(1,6)]

In [28]:
data = pd.DataFrame(columns=[wt+ko], index=genes)
data

wt1  wt2  wt3  wt4  wt5  ko1  ko2  ko3  ko4  ko5
gene1    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene2    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene3    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene4    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene5    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene6    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene7    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene8    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene9    NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene10   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene11   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene12   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene13   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene14   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene15   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene16   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene17   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene18   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene19   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene20   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene21   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene22   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene23   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene24   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene25   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene26   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene27   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene28   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene29   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene30   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
...      ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
gene71   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene72   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene73   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene74   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene75   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene76   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene77   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene78   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene79   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene80   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene81   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene82   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene83   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene84   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene85   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene86   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene87   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene88   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene89   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene90   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene91   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene92   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene93   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene94   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene95   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene96   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene97   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene98   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene99   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
gene100  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN

[100 rows x 10 columns]

In [56]:
for gene in data.index:
    data.loc[gene,0:5]=np.random.poisson(lam=rd.randrange(10,1000),size=5)
    data.loc[gene,5:10]=np.random.poisson(lam=rd.randrange(10,1000),size=5)
data.T

gene1  gene2  gene3  gene4  gene5  gene6  gene7  gene8  gene9  gene10  \
wt1    748    897    263     59    694    477    921    937     82     763   
wt2    806    914    238     57    714    520    848    927     96     761   
wt3    776    989    243     55    689    478    896    975     98     765   
wt4    746    974    215     54    661    565    878    958     92     725   
wt5    741    921    228     56    696    492    948    944     93     806   
ko1    674    486    883    339    216    154    879    716     70     163   
ko2    642    508    907    352    217    146    889    675     76     194   
ko3    685    505    848    360    205    136    882    752     67     176   
ko4    745    507    846    351    211    147    922    738     91     163   
ko5    670    537    877    350    217    166    878    735     73     150   

     ...  gene91  gene92  gene93  gene94  gene95  gene96  gene97  gene98  \
wt1  ...     621     471     316     321      99     657     222     721   
wt2  ...     592     489     290     311     110     679     220     657   
wt3  ...     584     425     314     345     108     682     172     650   
wt4  ...     645     468     292     312     108     720     202     655   
wt5  ...     639     443     324     334      98     639     207     657   
ko1  ...     760     492     506     758     165     274     443     541   
ko2  ...     720     543     514     732     151     275     411     578   
ko3  ...     739     470     498     781     146     284     414     557   
ko4  ...     742     491     533     766     150     277     419     553   
ko5  ...     720     486     493     790     173     268     438     557   

     gene99  gene100  
wt1     601      407  
wt2     646      467  
wt3     677      409  
wt4     648      476  
wt5     657      434  
ko1      20      295  
ko2      14      304  
ko3      13      289  
ko4      21      282  
ko5      10      313  

[10 rows x 100 columns]

In [61]:
scaled_data = preprocessing.StandardScaler().fit_transform(data.T)
scaled_data

array([[ 0.49524861,  0.7981638 , -0.91757032, -0.98042177,  1.01200323,
         0.82735131,  0.9852158 ,  0.88327018, -0.16379889,  0.99416616,
         0.9599636 ,  1.08920106,  1.33661573,  1.30835318,  1.01619485,
         1.1505572 , -1.07610423,  1.0780648 ,  0.9901559 , -1.76212486,
         0.99409239,  0.75895234, -1.03219633, -0.85230529,  0.87292041,
         0.79868964,  0.97458641,  1.37293683,  0.46083024, -0.12699731,
         0.64858448, -1.22994391,  0.81307243, -0.76122012,  0.4097328 ,
         0.88549406,  0.7671449 , -0.96362203, -1.0125868 , -1.03748692,
         1.20984456,  0.23917577, -1.09428094,  0.948386  ,  1.72549727,
        -1.41272663, -1.21041195, -0.92629209,  0.87323425, -0.95724186,
        -1.3515622 , -0.97518066, -0.88807261,  1.01220226,  0.86963348,
         1.27222834, -0.94376633, -1.13274835, -0.89743232,  1.13767739,
        -0.91049754, -1.08552262,  1.1368682 , -0.71078337,  0.96291808,
         1.12421262, -0.68372294, -0.86427087,  0.9

In [68]:
pca = PCA()
pca.fit(scaled_data)
pca_data = pca.transform(scaled_data)
pca_data

array([[  9.17968654e+00,   1.34991230e+00,   2.70712807e+00,
          1.56573363e+00,  -1.49471157e-01,   3.29028835e-01,
         -4.74287943e-01,  -8.73070461e-01,  -1.16249569e+00,
          2.41473508e-15],
       [  9.37592225e+00,   5.97106336e-01,  -2.27019085e+00,
         -1.25284257e+00,  -1.82003272e+00,   2.19978547e+00,
         -2.73879007e-01,  -1.56787306e-01,  -1.42611275e-01,
          4.10782519e-15],
       [  8.82262818e+00,  -3.25977369e-01,  -1.18616282e+00,
          2.67439591e+00,   1.43149618e+00,   4.50365799e-01,
          3.41408544e-01,   1.40599319e+00,   6.18866828e-01,
          2.49800181e-15],
       [  9.29097002e+00,  -3.19431041e+00,  -1.33669862e-01,
         -7.71315514e-01,  -2.37424748e-01,  -1.47981576e+00,
          1.86054676e+00,  -7.23199107e-01,  -1.86693160e-01,
          2.86316110e-15],
       [  9.64142812e+00,   1.57721196e+00,   8.80173155e-01,
         -2.07221315e+00,   7.80120394e-01,  -1.46321693e+00,
         -1.39539392e+00

In [59]:
scaled_data = preprocessing.scale(data.T)
scaled_data

array([[ 0.73691497,  0.94398642,  0.8366503 ,  0.72625302,  0.69161237,
         0.70052165,  0.55514491,  0.73087573,  0.92579179,  0.66379399],
       [ 1.26855846,  1.33269518,  1.59042118,  1.54054213,  1.32748032,
         0.03413461,  0.09157279,  0.09917674,  0.09237608,  0.20006565],
       [-0.99360244, -1.10033372, -1.04954634, -1.17018344, -1.12061128,
         1.44134554,  1.47191066,  1.30291426,  1.27946821,  1.38553659],
       [-1.72149017, -1.75178081, -1.71484646, -1.74518583, -1.72821843,
        -0.48692334, -0.44810818, -0.40969189, -0.45389641, -0.45194336],
       [ 0.5442388 ,  0.61286414,  0.52877205,  0.42268033,  0.53264539,
        -0.9229106 , -0.91513979, -0.95365491, -0.94414094, -0.9156717 ],
       [-0.23003393, -0.08537196, -0.21792118,  0.07982176, -0.18800496,
        -1.14267654, -1.16076382, -1.19580619, -1.16825273, -1.09349234],
       [ 1.35419231,  1.09515094,  1.26130995,  1.19768356,  1.42286052,
         1.4271671 ,  1.40963978,  1.42223518

In [1]:
git clone git@github.com:LIUNancy/data-processing.git

SyntaxError: invalid syntax (56555574.py, line 1)

In [2]:
install git

SyntaxError: invalid syntax (3510441910.py, line 1)